### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by meejah** [Edinburgh-Genome-Foundry/lala#1]
When trying to pip install, I get this:

```
$ pip install python-lala                                                 
Collecting python-lala
  Using cached python-lala-0.1.3.tar.gz (26 kB)
    ERROR: Command errored out with exit status 1:
     command: [redacted]/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wkmc6xu7/python-lala/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wkmc6xu7/python-lala/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-asc7g9e6                     
         cwd: /tmp/pip-install-wkmc6xu7/python-lala/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-wkmc6xu7/python-lala/setup.py", line 13, in <module>                                     
        long_description=open('pypi-readme.rst').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'pypi-readme.rst'                                         
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.  
```

This is probably because you haven't included `pypi-readme.rst` in the release .. or similar.

**Comment by veghp** [comment]
Thank you for bringing attention to this. I've updated the package on PyPI, so it should install properly now. However, unexpectedly the tests have failed, so I'll look into that now.
